#cloud-config

apt_update: true
apt_upgrade: true

packages:
  - apt-transport-https 
  - ca-certificates 
  - curl
  - software-properties-common
  - docker.io
  - nova-compute
  - python3-openstackclient
  - python3-pip

byobu_default: system

runcmd:
  # Download docker
  #- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #- add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  #- apt-get update -y
  #- apt-get install -y docker-ce
  # Download github repo
  - cd /home/ubuntu
  - su - ubuntu -c "git clone https://github.com/rajib13myself/DB-2.git"
  - cd DB-2
  - git config --global user.email rajib43.datta@gmail.com
  - git config --global user.name rajib13myself
  # Download k3s, setup clustere and make it accessible for non root users 
  - curl -sfL https://get.k3s.io | sh -
  - sudo chmod 644 /etc/rancher/k3s/k3s.yaml
  - echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> /home/ubuntu/.bashrc
  # Install helm
  - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

final_message: "The system is finally up, after $UPTIME seconds"
