apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: datta-namespace
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rajib43datta/test-python-app:latest  
          imagePullPolicy: Always
          ports:
          - containerPort: 5100
          env:
          - name: FLASK_ENV
            value: "development"  # or "production" if you want to switch to production mode
